# Generated by Django 4.0 on 2024-09-16 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('image', models.ImageField(upload_to=None)),
                ('desig', models.TextField()),
                ('univ', models.TextField()),
                ('link', models.URLField()),
            ],
        ),
    ]
