# Generated by Django 4.0 on 2024-09-16 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colab',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
