# Generated by Django 4.0 on 2024-09-16 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_rename_training_year_publication_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='link',
            field=models.URLField(default='nada'),
            preserve_default=False,
        ),
    ]
