# Generated by Django 4.0 on 2024-09-16 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_publication_authors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('short_desc', models.TextField(max_length=100)),
                ('long_desc', models.TextField(max_length=400)),
            ],
        ),
    ]
