# Generated by Django 4.0 on 2024-09-16 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_gallery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postdoc',
            old_name='desig',
            new_name='degree',
        ),
        migrations.AddField(
            model_name='gallery',
            name='date',
            field=models.DateField(default='2024-10-01'),
            preserve_default=False,
        ),
    ]
