# Generated by Django 4.0.6 on 2025-01-01 11:19

import django.core.validators
from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_alumni_mail_alter_phd_github_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='year',
            field=models.PositiveIntegerField(default=2025, validators=[django.core.validators.MinValueValidator(2005), home.models.max_value_current_year]),
        ),
    ]
