# Generated by Django 4.0.6 on 2025-01-04 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_publication_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
                ('description', models.TextField(max_length=2000)),
            ],
        ),
    ]
