# Generated by Django 4.0.6 on 2025-01-04 21:15

import collections
from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_research'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='publication',
            field=jsonfield.fields.JSONField(default='null', load_kwargs={'object_pairs_hook': collections.OrderedDict}),
            preserve_default=False,
        ),
    ]
