# Generated by Django 4.0.6 on 2025-01-04 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_research_publication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='research',
            name='publication',
        ),
        migrations.CreateModel(
            name='Publication_Research',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=255, verbose_name='Publications')),
                ('research', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.research', verbose_name='Link to Research')),
            ],
        ),
    ]
