# Generated by Django 4.0.6 on 2025-03-22 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_publication_created_at'),
        ('home', '0017_publication_created_at'),
    ]

    operations = [
    ]
