# Generated by Django 5.1.7 on 2025-03-24 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_merge_20250322_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='title',
            field=models.TextField(max_length=1000),
        ),
    ]
