# Generated by Django 4.0.6 on 2025-10-21 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_alter_publication_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoftwareProject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=10000)),
                ('tags', models.CharField(help_text='Comma-separated tags', max_length=200)),
                ('publication_url', models.URLField(blank=True, null=True)),
                ('repo_url', models.URLField(blank=True, null=True)),
                ('status', models.CharField(blank=True, help_text="e.g., 'In Progress'", max_length=50)),
                ('my_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['my_order'],
            },
        ),
        migrations.AddField(
            model_name='research',
            name='content',
            field=models.TextField(default='Hi', max_length=100000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='research',
            name='description',
            field=models.TextField(max_length=10000),
        ),
    ]
