# Generated by Django 4.0.6 on 2025-10-21 12:34

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_softwareproject_research_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
