# Generated by Django 4.0.6 on 2025-10-21 12:52

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_research_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='content',
            field=django_quill.fields.QuillField(),
        ),
    ]
