# Generated by Django 5.2.7 on 2025-10-21 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0022_alter_research_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="research",
            name="content",
            field=models.TextField(),
        ),
    ]
