# Generated by Django 5.2.7 on 2025-10-21 17:24

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0024_alter_research_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="research",
            name="content",
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
