# Generated by Django 5.2.7 on 2025-10-21 17:34

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0025_alter_research_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="research",
            name="content",
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name="Text"),
        ),
    ]
