# Generated by Django 5.2.7 on 2025-10-22 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0026_alter_research_content"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="alumni",
            options={"ordering": ["my_order"]},
        ),
        migrations.AlterModelOptions(
            name="colab",
            options={"ordering": ["my_order"]},
        ),
        migrations.AlterModelOptions(
            name="gallery",
            options={"ordering": ["my_order"]},
        ),
        migrations.AlterModelOptions(
            name="news",
            options={"ordering": ["my_order"]},
        ),
        migrations.AlterModelOptions(
            name="phd",
            options={"ordering": ["my_order"]},
        ),
        migrations.AlterModelOptions(
            name="postdoc",
            options={"ordering": ["my_order"]},
        ),
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ["my_order"]},
        ),
        migrations.AddField(
            model_name="alumni",
            name="my_order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="colab",
            name="my_order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="gallery",
            name="my_order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="news",
            name="my_order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="phd",
            name="my_order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="postdoc",
            name="my_order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="project",
            name="my_order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="alumni",
            name="desig",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="alumni",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="alumni",
            name="role",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="alumni",
            name="subject",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="colab",
            name="desig",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="colab",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="colab",
            name="univ",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="gallery",
            name="short_desc",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="news",
            name="title",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="phd",
            name="desig",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="phd",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="postdoc",
            name="degree",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="postdoc",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="project",
            name="desig",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="project",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="publication",
            name="title",
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="research",
            name="title",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="softwareproject",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
