# Generated by Django 5.2.7 on 2026-01-13 19:58

import django.core.validators
import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0027_alter_alumni_options_alter_colab_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Animation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="animations/")),
                ("short_desc", models.CharField(max_length=100)),
                ("long_desc", models.TextField(max_length=400)),
                ("date", models.DateField()),
                ("my_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["my_order", "-date"],
            },
        ),
        migrations.CreateModel(
            name="Poster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="posters/")),
                ("short_desc", models.CharField(max_length=100)),
                ("long_desc", models.TextField(max_length=400)),
                ("date", models.DateField()),
                ("my_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["my_order", "-date"],
            },
        ),
        migrations.AlterField(
            model_name="publication",
            name="year",
            field=models.PositiveIntegerField(
                default=2026,
                validators=[
                    django.core.validators.MinValueValidator(2005),
                    home.models.max_value_current_year,
                ],
            ),
        ),
    ]
