# Generated by Django 5.2.7 on 2026-01-13 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0028_animation_poster_alter_publication_year"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="alumni",
            options={"ordering": ["my_order"], "verbose_name_plural": "Alumni"},
        ),
        migrations.AlterModelOptions(
            name="news",
            options={"ordering": ["my_order"], "verbose_name_plural": "News"},
        ),
        migrations.AlterModelOptions(
            name="research",
            options={"verbose_name_plural": "Research"},
        ),
    ]
