# Generated by Django 5.2.7 on 2026-01-13 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0029_alter_alumni_options_alter_news_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="poster",
            name="image",
        ),
        migrations.AddField(
            model_name="poster",
            name="pdf",
            field=models.FileField(default=None, upload_to="posters/"),
            preserve_default=False,
        ),
    ]
