# Generated by Django 5.2.7 on 2026-01-13 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0030_remove_poster_image_poster_pdf"),
    ]

    operations = [
        migrations.AddField(
            model_name="poster",
            name="thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to="posters/thumbnails/"
            ),
        ),
        migrations.AlterField(
            model_name="poster",
            name="pdf",
            field=models.FileField(upload_to="posters/pdf/"),
        ),
    ]
