# Generated by Django 5.2.7 on 2026-01-13 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0031_poster_thumbnail_alter_poster_pdf"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="poster",
            name="thumbnail",
        ),
        migrations.AlterField(
            model_name="poster",
            name="long_desc",
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name="poster",
            name="pdf",
            field=models.FileField(upload_to="posters/"),
        ),
        migrations.AlterField(
            model_name="poster",
            name="short_desc",
            field=models.CharField(max_length=300),
        ),
    ]
