# Generated by Django 5.2.7 on 2026-01-13 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0032_remove_poster_thumbnail_alter_poster_long_desc_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectAlumni",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "duration",
                    models.CharField(
                        help_text="e.g. 'Summer 2023' or '2023-2024'", max_length=100
                    ),
                ),
                ("project_title", models.CharField(max_length=200)),
                ("current_position", models.CharField(blank=True, max_length=200)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="images/"),
                ),
                ("my_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Project Alumni",
                "ordering": ["my_order"],
            },
        ),
    ]
