# Generated by Django 5.2.7 on 2026-01-13 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0033_projectalumni"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projectalumni",
            name="image",
        ),
    ]
