# Generated by Django 5.2.7 on 2026-01-13 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0034_remove_projectalumni_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lab_title",
                    models.CharField(default="Chakrabarty Lab, 2024", max_length=200),
                ),
                (
                    "group_image",
                    models.ImageField(
                        help_text="Upload the main group photo", upload_to="images/"
                    ),
                ),
                (
                    "group_caption",
                    models.TextField(
                        help_text="Caption map for the group photo (e.g. '(From left) Name1, Name2...')"
                    ),
                ),
                (
                    "pi_name",
                    models.CharField(default="Dr. Suman Chakrabarty", max_length=100),
                ),
                (
                    "pi_role",
                    models.CharField(
                        default="Professor & Group Leader", max_length=100
                    ),
                ),
                (
                    "pi_image",
                    models.ImageField(
                        help_text="Upload PI's photo", upload_to="images/"
                    ),
                ),
                (
                    "pi_department",
                    models.CharField(
                        default="Department of Chemical and Biological Sciences",
                        max_length=200,
                    ),
                ),
                (
                    "pi_department_url",
                    models.URLField(
                        blank=True,
                        default="https://newweb.bose.res.in/departments/CBS/Faculty.jsp",
                    ),
                ),
                (
                    "pi_institute",
                    models.CharField(
                        default="S. N. Bose National Centre for Basic Sciences, Kolkata",
                        max_length=200,
                    ),
                ),
                (
                    "pi_institute_url",
                    models.URLField(blank=True, default="https://newweb.bose.res.in"),
                ),
                (
                    "research_interests",
                    models.TextField(
                        help_text="Comma separated list of interests or full text"
                    ),
                ),
                (
                    "email",
                    models.EmailField(default="sumanc@bose.res.in", max_length=254),
                ),
                (
                    "google_scholar",
                    models.URLField(blank=True, verbose_name="Google Scholar URL"),
                ),
                ("linkedin", models.URLField(blank=True, verbose_name="LinkedIn URL")),
                ("twitter", models.URLField(blank=True, verbose_name="Twitter/X URL")),
                ("github", models.URLField(blank=True, verbose_name="GitHub URL")),
            ],
            options={
                "verbose_name": "Team Page Configuration",
                "verbose_name_plural": "Team Page Configuration",
            },
        ),
    ]
