# Generated by Django 5.2.7 on 2026-01-14 14:39

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0035_teampage"),
    ]

    operations = [
        migrations.CreateModel(
            name="HeroSlide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Background image for the slide",
                        null=True,
                        upload_to="sliders/",
                    ),
                ),
                (
                    "video",
                    models.FileField(
                        blank=True,
                        help_text="Upload MP4/WebM video (overrides image)",
                        null=True,
                        upload_to="sliders/videos/",
                    ),
                ),
                (
                    "caption_title",
                    models.CharField(
                        blank=True,
                        help_text="Main heading in the caption",
                        max_length=200,
                    ),
                ),
                (
                    "caption_subtitle",
                    models.CharField(
                        blank=True,
                        help_text="Subheading in the caption",
                        max_length=200,
                    ),
                ),
                ("my_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Hero Slide",
                "verbose_name_plural": "Hero Slides",
                "ordering": ["my_order"],
            },
        ),
        migrations.CreateModel(
            name="HomePageConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("about_title", models.CharField(default="About Us", max_length=200)),
                (
                    "about_image",
                    models.ImageField(
                        help_text="Upload the About Section image", upload_to="images/"
                    ),
                ),
                (
                    "about_content",
                    django_ckeditor_5.fields.CKEditor5Field(
                        verbose_name="About Content"
                    ),
                ),
                (
                    "research_title",
                    models.CharField(default="Research", max_length=200),
                ),
                (
                    "research_heading",
                    models.CharField(
                        default="Major Research Interests", max_length=200
                    ),
                ),
                (
                    "research_description",
                    django_ckeditor_5.fields.CKEditor5Field(
                        verbose_name="Research Description"
                    ),
                ),
            ],
            options={
                "verbose_name": "Home Page Configuration",
                "verbose_name_plural": "Home Page Configuration",
            },
        ),
    ]
