# Generated by Django 5.2.7 on 2026-03-21 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0036_heroslide_homepageconfiguration"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="research",
            options={"ordering": ["my_order"], "verbose_name_plural": "Research"},
        ),
        migrations.AddField(
            model_name="research",
            name="my_order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
