# Generated by Django 5.2.7 on 2026-03-21 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0037_alter_research_options_research_my_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="publication_research",
            name="url",
            field=models.URLField(
                blank=True,
                help_text="Optional link to the publication",
                null=True,
                verbose_name="Publication URL",
            ),
        ),
    ]
