# Generated by Django 5.2.7 on 2026-03-21 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0038_publication_research_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="research",
            name="selected_publications",
            field=models.ManyToManyField(
                blank=True, related_name="research_topics", to="home.publication"
            ),
        ),
    ]
