# Generated by Django 4.0 on 2024-09-16 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_publication'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='training_year',
            new_name='year',
        ),
    ]
