# Generated by Django 4.2.7 on 2024-10-08 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0011_rename_desig_postdoc_degree_gallery_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alumni",
            name="mail",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="phd",
            name="github",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="phd",
            name="linkedin",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="phd",
            name="mail",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="phd",
            name="twitter",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="postdoc",
            name="github",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="postdoc",
            name="linkedin",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="postdoc",
            name="mail",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="postdoc",
            name="twitter",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="github",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="linkedin",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="mail",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="twitter",
            field=models.URLField(blank=True, null=True),
        ),
    ]
